export const SecurityEvent = {
  // Authentication
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_BRUTE_FORCE_DETECTED: "AUTH_BRUTE_FORCE_DETECTED",
  AUTH_NEW_IP_LOGIN: "AUTH_NEW_IP_LOGIN",
  AUTH_SUSPICIOUS_IP_LOGIN: "AUTH_SUSPICIOUS_IP_LOGIN",
  AUTH_IMPOSSIBLE_TRAVEL: "AUTH_IMPOSSIBLE_TRAVEL",
  AUTH_REFRESH_TOKEN_ROTATED: "AUTH_REFRESH_TOKEN_ROTATED",
  AUTH_REFRESH_TOKEN_REUSE_DETECTED: "AUTH_REFRESH_TOKEN_REUSE_DETECTED",
  AUTH_LOGOUT: "AUTH_LOGOUT",

  // Session / Token
  SESSION_REVOKED: "SESSION_REVOKED",
  SESSION_REVOKED_BY_IP: "SESSION_REVOKED_BY_IP",
  SESSION_EXPIRED_ACCESS_ATTEMPT: "SESSION_EXPIRED_ACCESS_ATTEMPT",
  TOKEN_REPLAY_DETECTED: "TOKEN_REPLAY_DETECTED",

  // File access
  FILE_UPLOAD_INITIATED: "FILE_UPLOAD_INITIATED",
  FILE_UPLOAD_COMPLETED: "FILE_UPLOAD_COMPLETED",
  FILE_UPLOAD_COMPLETE_DENIED: "FILE_UPLOAD_COMPLETE_DENIED",
  FILE_DOWNLOAD_REQUESTED: "FILE_DOWNLOAD_REQUESTED",
  FILE_DOWNLOAD_DENIED: "FILE_DOWNLOAD_DENIED",
  FILE_DOWNLOAD_DENIED_RESTRICTED: "FILE_DOWNLOAD_DENIED_RESTRICTED",
  FILE_DOWNLOAD_SECURITY_OVERRIDE: "FILE_DOWNLOAD_SECURITY_OVERRIDE",
  FILE_DOWNLOAD_SPIKE_DETECTED: "FILE_DOWNLOAD_SPIKE_DETECTED",
  FILE_FLAGGED_FOR_INVESTIGATION: "FILE_FLAGGED_FOR_INVESTIGATION",
  FILE_ACCESS_RESTRICTED: "FILE_ACCESS_RESTRICTED",

  // Policy / RBAC
  POLICY_VIOLATION: "POLICY_VIOLATION",
  ROLE_POLICY_VIOLATION: "ROLE_POLICY_VIOLATION",
  UNAUTHORIZED_ADMIN_ACCESS_ATTEMPT: "UNAUTHORIZED_ADMIN_ACCESS_ATTEMPT",

  // Risk / Detection
  RISK_SCORE_EVALUATED: "RISK_SCORE_EVALUATED",
  SECURITY_ALERT_TRIGGERED: "SECURITY_ALERT_TRIGGERED",
  THREAT_PATTERN_CORRELATED: "THREAT_PATTERN_CORRELATED",
  BEHAVIORAL_THREAT_CORRELATED: "BEHAVIORAL_THREAT_CORRELATED",

  // Containment / Response
  AUTOMATED_CONTAINMENT_TRIGGERED: "AUTOMATED_CONTAINMENT_TRIGGERED",
  TARGETED_CONTAINMENT_TRIGGERED: "TARGETED_CONTAINMENT_TRIGGERED",
  IP_BASED_CONTAINMENT_TRIGGERED: "IP_BASED_CONTAINMENT_TRIGGERED",
  IP_CONTAINMENT_MANUAL: "IP_CONTAINMENT_MANUAL",
  USER_ACCOUNT_LOCKED: "USER_ACCOUNT_LOCKED",
  USER_ACCOUNT_LOCKED_MANUALLY: "USER_ACCOUNT_LOCKED_MANUALLY",
  USER_ACCOUNT_UNLOCKED: "USER_ACCOUNT_UNLOCKED",
} as const;

export type SecurityEventType =
  (typeof SecurityEvent)[keyof typeof SecurityEvent];

export const SecurityEventCategory = {
  AUTHENTICATION: "authentication",
  SESSION: "session",
  FILE_ACCESS: "file_access",
  POLICY: "policy",
  RISK: "risk",
  CONTAINMENT: "containment",
} as const;

export type SecurityEventCategoryType =
  (typeof SecurityEventCategory)[keyof typeof SecurityEventCategory];

export function getSecurityEventCategory(
  eventType: SecurityEventType | string
): SecurityEventCategoryType {
  if (eventType.startsWith("AUTH_")) {
    return SecurityEventCategory.AUTHENTICATION;
  }

  if (
    eventType.startsWith("SESSION_") ||
    eventType.startsWith("TOKEN_")
  ) {
    return SecurityEventCategory.SESSION;
  }

  if (eventType.startsWith("FILE_")) {
    return SecurityEventCategory.FILE_ACCESS;
  }

  if (
    eventType.includes("POLICY") ||
    eventType.includes("UNAUTHORIZED")
  ) {
    return SecurityEventCategory.POLICY;
  }

  if (
    eventType.startsWith("RISK_") ||
    eventType.startsWith("SECURITY_ALERT")
  ) {
    return SecurityEventCategory.RISK;
  }

  return SecurityEventCategory.CONTAINMENT;
}