export const RiskSignal = {
  // Authentication
  FAILED_LOGIN_BURST: "FAILED_LOGIN_BURST",
  BRUTE_FORCE_AGAINST_USER: "BRUTE_FORCE_AGAINST_USER",
  NEW_IP_LOGIN: "NEW_IP_LOGIN",
  SUSPICIOUS_IP_LOGIN: "SUSPICIOUS_IP_LOGIN",
  IMPOSSIBLE_TRAVEL: "IMPOSSIBLE_TRAVEL",

  // Session / Token
  REFRESH_TOKEN_REUSE: "REFRESH_TOKEN_REUSE",
  REVOKED_SESSION_ACCESS: "REVOKED_SESSION_ACCESS",
  TOKEN_REPLAY: "TOKEN_REPLAY",

  // File
  DOWNLOAD_SPIKE: "DOWNLOAD_SPIKE",
  SENSITIVE_FILE_ACCESS: "SENSITIVE_FILE_ACCESS",
  SECURITY_OVERRIDE: "SECURITY_OVERRIDE",
  RESTRICTED_FILE_ACCESS: "RESTRICTED_FILE_ACCESS",
  OUTSIDE_DEPARTMENT_ACCESS: "OUTSIDE_DEPARTMENT_ACCESS",

  // Policy
  ROLE_POLICY_VIOLATION: "ROLE_POLICY_VIOLATION",
  UNAUTHORIZED_ADMIN_ACCESS: "UNAUTHORIZED_ADMIN_ACCESS",

  // Behavior
  UNUSUAL_ACTIVITY_BURST: "UNUSUAL_ACTIVITY_BURST",
  MULTIPLE_DENIED_ACTIONS: "MULTIPLE_DENIED_ACTIONS",
} as const;

export type RiskSignalType = (typeof RiskSignal)[keyof typeof RiskSignal];

export const RiskSignalWeight: Record<RiskSignalType, number> = {
  FAILED_LOGIN_BURST: 35,
  BRUTE_FORCE_AGAINST_USER: 60,
  NEW_IP_LOGIN: 20,
  SUSPICIOUS_IP_LOGIN: 35,
  IMPOSSIBLE_TRAVEL: 80,

  REFRESH_TOKEN_REUSE: 90,
  REVOKED_SESSION_ACCESS: 50,
  TOKEN_REPLAY: 90,

  DOWNLOAD_SPIKE: 55,
  SENSITIVE_FILE_ACCESS: 30,
  SECURITY_OVERRIDE: 25,
  RESTRICTED_FILE_ACCESS: 70,
  OUTSIDE_DEPARTMENT_ACCESS: 35,

  ROLE_POLICY_VIOLATION: 45,
  UNAUTHORIZED_ADMIN_ACCESS: 50,

  UNUSUAL_ACTIVITY_BURST: 40,
  MULTIPLE_DENIED_ACTIONS: 35,
};

export function scoreRiskSignals(signals: RiskSignalType[]): number {
  return signals.reduce((total, signal) => {
    return total + RiskSignalWeight[signal];
  }, 0);
}